{% set name = "dupin" %}
{% set version = "0.1.0" %}
{% set sha256 = "73bdb419fef6ad2d2a3b198a05745e9adda232adf5f2f0b8a2b32ca72d7a8d2a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/dupin/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0.0
    - pip
  run:
    - python >=3.9
    - bottleneck
    - freud
    - kneed
    - numpy
    - pandas
    - ruptures
    - scikit-learn

test:
  imports:
    - dupin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/glotzerlab/dupin
  summary: Offline and online event detection scheme for rare events in molecular simulations.
  doc_url: https://dupin.readthedocs.io
  dev_url: https://github.com/glotzerlab/dupin
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - b-butler
    - DomFijan
    - joaander
